language: objective-c
osx_image: xcode8.3
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script:
- ./build.sh aleph7/AIImageCompare
deploy:
  provider: releases
  api_key:
    secure: SgPWtI50z0/ASnIEHeXx94tpbEaC07rBAyqqCoQK1kmlPnmZ9H1U8d0PT6Grl6+ZWHCVzUbs0Ta8uXxLj4faoUZY5w4q5diPirEaDhsO9KTutFVtmd8Y3OWWf64yy2Mvlxz/Z6VNYkGmM4Nwof9U+ZTSZRz7rtYhZ2uXlq56byEx3UbAj8HhhT6zxk9WGitIHymmKO0Hh8p9x1dwQ4Q8ZugWYvghnnl9iDe2BcElDz+sZnrUR9Herd4LFtMFSceKzjiPTRb3E/nMMgsZv7y/yguKSxf2HMaT/5WcviNcDI8ADFESBWMJQNyiiN72Iq5LE85+wgrh5QVHzqyNQg6yI+GTuE7QkbmbAG2BlF6+geykfqbjj0ucyUAOtiLs7xxfkU+I7uTCJuphmK+7lpPfrEJtO2IoLrjyzySz+QeuoOb9tKevUeI6TRh+usrK3qX/8Fe9XWEx7QkV3ykvKnuDO53aUts8QW5rMmdQ1A6dtM6QXkQoz8fr2o/D0vLMHZJG/Ip4vzsgo/SLinjABZLannt9J23dpUU3DaGJqp2JxVHyE1JuIpdTYi1dOdhVxOqDQLO7ygVVOHE+Pcs+oYtYk4y8hr5UV0g1D+D7Ugbc84decLfHEWcLxQbs2eVFAZUGzfwBzxuPIvphzLPLFmB7UIm02RKeIESqSSmrkr1Oq7E=
  file_glob: true
  file: Archives/*
  skip_cleanup: true
  on:
    tags: true
