language: objective-c
osx_image: xcode8.3
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script:
- ./build.sh aleph7/AIImageCompare
deploy:
  provider: releases
  api_key:
    secure: K1VQL/QCMUS2BzmC28mQYO9WgMhcALDgO8FRDLgjd7bsmEP9n7STxghe4vJiTgVWsUWfTQTu7dIAi6mnrXPrEsHPcYV4gVlq1TTcmKI85fMiXa/GB5sP6gAsyC/7l38gmNTs+TBhSm1rqBoaJypPLhqYIwj2UbBiAlybXEbEerZwvVkmmmH1XfbvORacRW8sK5cFOHHF/xMjUGoWhucx5WoC755h1tK8QV3NKZr8raEPcN4Dt5MK+6y8qJezVLtaj48xHoXZqANb8D/HKKbNRhEWgPSmTpv9MkcYgfGjsSfKkDgF/+pTWjLCGzS0uhBGY6WzILZ+WKhLLtegO3A7oA4YFRFySS93j5TteLYeJnNBnJNopocEySrr3bUFsCSKub3h0404zJWh1IbjTkBf7+VvutUPi5m1OW2wxSclhn+A400K1WB9GTiuUVU/uE0uL8hmZRpO3Z3KMd4EbZMdo2M09p6V/zN5iOClnHl+yLu9/xd9sUJnQD8bHFUJIJXTIGpE1wGu12I0uoJcjzmtrEu8Qy+PoKdQuBaeWb0+cGvOEUmZ7jnyqzpp0r/xalo2K9ijmpVMOdqsCICOmGSr9DOaAJv5WJXOMDPVlhqDhn1Lssrc9mQ4ZyPo0FuBZEJuMNTfo0xU25pjNc4tFOl51x9J5z/Moc6I8V5DRsZ6z44=
  file_glob: true
  file: Archives/*
  skip_cleanup: true
  on:
    tags: true
